unit confname;

interface

{$IFDEF FPC}
{$PACKRECORDS C}
{$ENDIF}


{ `sysconf', `pathconf', and `confstr' NAME values.  Generic version.
   Copyright (C) 1993-2022 Free Software Foundation, Inc.
   This file is part of the GNU C Library.

   The GNU C Library is free software; you can redistribute it and/or
   modify it under the terms of the GNU Lesser General Public
   License as published by the Free Software Foundation; either
   version 2.1 of the License, or (at your option) any later version.

   The GNU C Library is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   Lesser General Public License for more details.

   You should have received a copy of the GNU Lesser General Public
   License along with the GNU C Library; if not, see
   <https://www.gnu.org/licenses/>.   }
{ Values for the NAME argument to `pathconf' and `fpathconf'.   }

const
  _PC_LINK_MAX = 0;
  _PC_MAX_CANON = 1;
  _PC_MAX_INPUT = 2;
  _PC_NAME_MAX = 3;
  _PC_PATH_MAX = 4;
  _PC_PIPE_BUF = 5;
  _PC_CHOWN_RESTRICTED = 6;
  _PC_NO_TRUNC = 7;
  _PC_VDISABLE = 8;
  _PC_SYNC_IO = 9;
  _PC_ASYNC_IO = 10;
  _PC_PRIO_IO = 11;
  _PC_SOCK_MAXBUF = 12;
  _PC_FILESIZEBITS = 13;
  _PC_REC_INCR_XFER_SIZE = 14;
  _PC_REC_MAX_XFER_SIZE = 15;
  _PC_REC_MIN_XFER_SIZE = 16;
  _PC_REC_XFER_ALIGN = 17;
  _PC_ALLOC_SIZE_MIN = 18;
  _PC_SYMLINK_MAX = 19;
  _PC_2_SYMLINKS = 20;

  { Values for the argument to `sysconf'.   }
const
  _SC_ARG_MAX = 0;
  _SC_CHILD_MAX = 1;
  _SC_CLK_TCK = 2;
  _SC_NGROUPS_MAX = 3;
  _SC_OPEN_MAX = 4;
  _SC_STREAM_MAX = 5;
  _SC_TZNAME_MAX = 6;
  _SC_JOB_CONTROL = 7;
  _SC_SAVED_IDS = 8;
  _SC_REALTIME_SIGNALS = 9;
  _SC_PRIORITY_SCHEDULING = 10;
  _SC_TIMERS = 11;
  _SC_ASYNCHRONOUS_IO = 12;
  _SC_PRIORITIZED_IO = 13;
  _SC_SYNCHRONIZED_IO = 14;
  _SC_FSYNC = 15;
  _SC_MAPPED_FILES = 16;
  _SC_MEMLOCK = 17;
  _SC_MEMLOCK_RANGE = 18;
  _SC_MEMORY_PROTECTION = 19;
  _SC_MESSAGE_PASSING = 20;
  _SC_SEMAPHORES = 21;
  _SC_SHARED_MEMORY_OBJECTS = 22;
  _SC_AIO_LISTIO_MAX = 23;
  _SC_AIO_MAX = 24;
  _SC_AIO_PRIO_DELTA_MAX = 25;
  _SC_DELAYTIMER_MAX = 26;
  _SC_MQ_OPEN_MAX = 27;
  _SC_MQ_PRIO_MAX = 28;
  _SC_VERSION = 29;
  _SC_PAGESIZE = 30;
  _SC_RTSIG_MAX = 31;
  _SC_SEM_NSEMS_MAX = 32;
  _SC_SEM_VALUE_MAX = 33;
  _SC_SIGQUEUE_MAX = 34;
  _SC_TIMER_MAX = 35;
  _SC_BC_BASE_MAX = 36;
  _SC_BC_DIM_MAX = 37;
  _SC_BC_SCALE_MAX = 38;
  _SC_BC_STRING_MAX = 39;
  _SC_COLL_WEIGHTS_MAX = 40;
  _SC_EQUIV_CLASS_MAX = 41;
  _SC_EXPR_NEST_MAX = 42;
  _SC_LINE_MAX = 43;
  _SC_RE_DUP_MAX = 44;
  _SC_CHARCLASS_NAME_MAX = 45;
  _SC_2_VERSION = 46;
  _SC_2_C_BIND = 47;
  _SC_2_C_DEV = 48;
  _SC_2_FORT_DEV = 49;
  _SC_2_FORT_RUN = 50;
  _SC_2_SW_DEV = 51;
  _SC_2_LOCALEDEF = 52;
  _SC_PII = 53;
  _SC_PII_XTI = 54;
  _SC_PII_SOCKET = 55;
  _SC_PII_INTERNET = 56;
  _SC_PII_OSI = 57;
  _SC_POLL = 58;
  _SC_SELECT = 59;
  _SC_UIO_MAXIOV = 60;
  _SC_IOV_MAX = _SC_UIO_MAXIOV;
  _SC_PII_INTERNET_STREAM = (_SC_UIO_MAXIOV) + 1;
  _SC_PII_INTERNET_DGRAM = (_SC_UIO_MAXIOV) + 2;
  _SC_PII_OSI_COTS = (_SC_UIO_MAXIOV) + 3;
  _SC_PII_OSI_CLTS = (_SC_UIO_MAXIOV) + 4;
  _SC_PII_OSI_M = (_SC_UIO_MAXIOV) + 5;
  _SC_T_IOV_MAX = (_SC_UIO_MAXIOV) + 6;
  _SC_THREADS = (_SC_UIO_MAXIOV) + 7;
  _SC_THREAD_SAFE_FUNCTIONS = (_SC_UIO_MAXIOV) + 8;
  _SC_GETGR_R_SIZE_MAX = (_SC_UIO_MAXIOV) + 9;
  _SC_GETPW_R_SIZE_MAX = (_SC_UIO_MAXIOV) + 10;
  _SC_LOGIN_NAME_MAX = (_SC_UIO_MAXIOV) + 11;
  _SC_TTY_NAME_MAX = (_SC_UIO_MAXIOV) + 12;
  _SC_THREAD_DESTRUCTOR_ITERATIONS = (_SC_UIO_MAXIOV) + 13;
  _SC_THREAD_KEYS_MAX = (_SC_UIO_MAXIOV) + 14;
  _SC_THREAD_STACK_MIN = (_SC_UIO_MAXIOV) + 15;
  _SC_THREAD_THREADS_MAX = (_SC_UIO_MAXIOV) + 16;
  _SC_THREAD_ATTR_STACKADDR = (_SC_UIO_MAXIOV) + 17;
  _SC_THREAD_ATTR_STACKSIZE = (_SC_UIO_MAXIOV) + 18;
  _SC_THREAD_PRIORITY_SCHEDULING = (_SC_UIO_MAXIOV) + 19;
  _SC_THREAD_PRIO_INHERIT = (_SC_UIO_MAXIOV) + 20;
  _SC_THREAD_PRIO_PROTECT = (_SC_UIO_MAXIOV) + 21;
  _SC_THREAD_PROCESS_SHARED = (_SC_UIO_MAXIOV) + 22;
  _SC_NPROCESSORS_CONF = (_SC_UIO_MAXIOV) + 23;
  _SC_NPROCESSORS_ONLN = (_SC_UIO_MAXIOV) + 24;
  _SC_PHYS_PAGES = (_SC_UIO_MAXIOV) + 25;
  _SC_AVPHYS_PAGES = (_SC_UIO_MAXIOV) + 26;
  _SC_ATEXIT_MAX = (_SC_UIO_MAXIOV) + 27;
  _SC_PASS_MAX = (_SC_UIO_MAXIOV) + 28;
  _SC_XOPEN_VERSION = (_SC_UIO_MAXIOV) + 29;
  _SC_XOPEN_XCU_VERSION = (_SC_UIO_MAXIOV) + 30;
  _SC_XOPEN_UNIX = (_SC_UIO_MAXIOV) + 31;
  _SC_XOPEN_CRYPT = (_SC_UIO_MAXIOV) + 32;
  _SC_XOPEN_ENH_I18N = (_SC_UIO_MAXIOV) + 33;
  _SC_XOPEN_SHM = (_SC_UIO_MAXIOV) + 34;
  _SC_2_CHAR_TERM = (_SC_UIO_MAXIOV) + 35;
  _SC_2_C_VERSION = (_SC_UIO_MAXIOV) + 36;
  _SC_2_UPE = (_SC_UIO_MAXIOV) + 37;
  _SC_XOPEN_XPG2 = (_SC_UIO_MAXIOV) + 38;
  _SC_XOPEN_XPG3 = (_SC_UIO_MAXIOV) + 39;
  _SC_XOPEN_XPG4 = (_SC_UIO_MAXIOV) + 40;
  _SC_CHAR_BIT = (_SC_UIO_MAXIOV) + 41;
  _SC_CHAR_MAX = (_SC_UIO_MAXIOV) + 42;
  _SC_CHAR_MIN = (_SC_UIO_MAXIOV) + 43;
  _SC_INT_MAX = (_SC_UIO_MAXIOV) + 44;
  _SC_INT_MIN = (_SC_UIO_MAXIOV) + 45;
  _SC_LONG_BIT = (_SC_UIO_MAXIOV) + 46;
  _SC_WORD_BIT = (_SC_UIO_MAXIOV) + 47;
  _SC_MB_LEN_MAX = (_SC_UIO_MAXIOV) + 48;
  _SC_NZERO = (_SC_UIO_MAXIOV) + 49;
  _SC_SSIZE_MAX = (_SC_UIO_MAXIOV) + 50;
  _SC_SCHAR_MAX = (_SC_UIO_MAXIOV) + 51;
  _SC_SCHAR_MIN = (_SC_UIO_MAXIOV) + 52;
  _SC_SHRT_MAX = (_SC_UIO_MAXIOV) + 53;
  _SC_SHRT_MIN = (_SC_UIO_MAXIOV) + 54;
  _SC_UCHAR_MAX = (_SC_UIO_MAXIOV) + 55;
  _SC_UINT_MAX = (_SC_UIO_MAXIOV) + 56;
  _SC_ULONG_MAX = (_SC_UIO_MAXIOV) + 57;
  _SC_USHRT_MAX = (_SC_UIO_MAXIOV) + 58;
  _SC_NL_ARGMAX = (_SC_UIO_MAXIOV) + 59;
  _SC_NL_LANGMAX = (_SC_UIO_MAXIOV) + 60;
  _SC_NL_MSGMAX = (_SC_UIO_MAXIOV) + 61;
  _SC_NL_NMAX = (_SC_UIO_MAXIOV) + 62;
  _SC_NL_SETMAX = (_SC_UIO_MAXIOV) + 63;
  _SC_NL_TEXTMAX = (_SC_UIO_MAXIOV) + 64;
  _SC_XBS5_ILP32_OFF32 = (_SC_UIO_MAXIOV) + 65;
  _SC_XBS5_ILP32_OFFBIG = (_SC_UIO_MAXIOV) + 66;
  _SC_XBS5_LP64_OFF64 = (_SC_UIO_MAXIOV) + 67;
  _SC_XBS5_LPBIG_OFFBIG = (_SC_UIO_MAXIOV) + 68;
  _SC_XOPEN_LEGACY = (_SC_UIO_MAXIOV) + 69;
  _SC_XOPEN_REALTIME = (_SC_UIO_MAXIOV) + 70;
  _SC_XOPEN_REALTIME_THREADS = (_SC_UIO_MAXIOV) + 71;
  _SC_ADVISORY_INFO = (_SC_UIO_MAXIOV) + 72;
  _SC_BARRIERS = (_SC_UIO_MAXIOV) + 73;
  _SC_BASE = (_SC_UIO_MAXIOV) + 74;
  _SC_C_LANG_SUPPORT = (_SC_UIO_MAXIOV) + 75;
  _SC_C_LANG_SUPPORT_R = (_SC_UIO_MAXIOV) + 76;
  _SC_CLOCK_SELECTION = (_SC_UIO_MAXIOV) + 77;
  _SC_CPUTIME = (_SC_UIO_MAXIOV) + 78;
  _SC_THREAD_CPUTIME = (_SC_UIO_MAXIOV) + 79;
  _SC_DEVICE_IO = (_SC_UIO_MAXIOV) + 80;
  _SC_DEVICE_SPECIFIC = (_SC_UIO_MAXIOV) + 81;
  _SC_DEVICE_SPECIFIC_R = (_SC_UIO_MAXIOV) + 82;
  _SC_FD_MGMT = (_SC_UIO_MAXIOV) + 83;
  _SC_FIFO = (_SC_UIO_MAXIOV) + 84;
  _SC_PIPE = (_SC_UIO_MAXIOV) + 85;
  _SC_FILE_ATTRIBUTES = (_SC_UIO_MAXIOV) + 86;
  _SC_FILE_LOCKING = (_SC_UIO_MAXIOV) + 87;
  _SC_FILE_SYSTEM = (_SC_UIO_MAXIOV) + 88;
  _SC_MONOTONIC_CLOCK = (_SC_UIO_MAXIOV) + 89;
  _SC_MULTI_PROCESS = (_SC_UIO_MAXIOV) + 90;
  _SC_SINGLE_PROCESS = (_SC_UIO_MAXIOV) + 91;
  _SC_NETWORKING = (_SC_UIO_MAXIOV) + 92;
  _SC_READER_WRITER_LOCKS = (_SC_UIO_MAXIOV) + 93;
  _SC_SPIN_LOCKS = (_SC_UIO_MAXIOV) + 94;
  _SC_REGEXP = (_SC_UIO_MAXIOV) + 95;
  _SC_REGEX_VERSION = (_SC_UIO_MAXIOV) + 96;
  _SC_SHELL = (_SC_UIO_MAXIOV) + 97;
  _SC_SIGNALS = (_SC_UIO_MAXIOV) + 98;
  _SC_SPAWN = (_SC_UIO_MAXIOV) + 99;
  _SC_SPORADIC_SERVER = (_SC_UIO_MAXIOV) + 100;
  _SC_THREAD_SPORADIC_SERVER = (_SC_UIO_MAXIOV) + 101;
  _SC_SYSTEM_DATABASE = (_SC_UIO_MAXIOV) + 102;
  _SC_SYSTEM_DATABASE_R = (_SC_UIO_MAXIOV) + 103;
  _SC_TIMEOUTS = (_SC_UIO_MAXIOV) + 104;
  _SC_TYPED_MEMORY_OBJECTS = (_SC_UIO_MAXIOV) + 105;
  _SC_USER_GROUPS = (_SC_UIO_MAXIOV) + 106;
  _SC_USER_GROUPS_R = (_SC_UIO_MAXIOV) + 107;
  _SC_2_PBS = (_SC_UIO_MAXIOV) + 108;
  _SC_2_PBS_ACCOUNTING = (_SC_UIO_MAXIOV) + 109;
  _SC_2_PBS_LOCATE = (_SC_UIO_MAXIOV) + 110;
  _SC_2_PBS_MESSAGE = (_SC_UIO_MAXIOV) + 111;
  _SC_2_PBS_TRACK = (_SC_UIO_MAXIOV) + 112;
  _SC_SYMLOOP_MAX = (_SC_UIO_MAXIOV) + 113;
  _SC_STREAMS = (_SC_UIO_MAXIOV) + 114;
  _SC_2_PBS_CHECKPOINT = (_SC_UIO_MAXIOV) + 115;
  _SC_V6_ILP32_OFF32 = (_SC_UIO_MAXIOV) + 116;
  _SC_V6_ILP32_OFFBIG = (_SC_UIO_MAXIOV) + 117;
  _SC_V6_LP64_OFF64 = (_SC_UIO_MAXIOV) + 118;
  _SC_V6_LPBIG_OFFBIG = (_SC_UIO_MAXIOV) + 119;
  _SC_HOST_NAME_MAX = (_SC_UIO_MAXIOV) + 120;
  _SC_TRACE = (_SC_UIO_MAXIOV) + 121;
  _SC_TRACE_EVENT_FILTER = (_SC_UIO_MAXIOV) + 122;
  _SC_TRACE_INHERIT = (_SC_UIO_MAXIOV) + 123;
  _SC_TRACE_LOG = (_SC_UIO_MAXIOV) + 124;
  _SC_LEVEL1_ICACHE_SIZE = (_SC_UIO_MAXIOV) + 125;
  _SC_LEVEL1_ICACHE_ASSOC = (_SC_UIO_MAXIOV) + 126;
  _SC_LEVEL1_ICACHE_LINESIZE = (_SC_UIO_MAXIOV) + 127;
  _SC_LEVEL1_DCACHE_SIZE = (_SC_UIO_MAXIOV) + 128;
  _SC_LEVEL1_DCACHE_ASSOC = (_SC_UIO_MAXIOV) + 129;
  _SC_LEVEL1_DCACHE_LINESIZE = (_SC_UIO_MAXIOV) + 130;
  _SC_LEVEL2_CACHE_SIZE = (_SC_UIO_MAXIOV) + 131;
  _SC_LEVEL2_CACHE_ASSOC = (_SC_UIO_MAXIOV) + 132;
  _SC_LEVEL2_CACHE_LINESIZE = (_SC_UIO_MAXIOV) + 133;
  _SC_LEVEL3_CACHE_SIZE = (_SC_UIO_MAXIOV) + 134;
  _SC_LEVEL3_CACHE_ASSOC = (_SC_UIO_MAXIOV) + 135;
  _SC_LEVEL3_CACHE_LINESIZE = (_SC_UIO_MAXIOV) + 136;
  _SC_LEVEL4_CACHE_SIZE = (_SC_UIO_MAXIOV) + 137;
  _SC_LEVEL4_CACHE_ASSOC = (_SC_UIO_MAXIOV) + 138;
  _SC_LEVEL4_CACHE_LINESIZE = (_SC_UIO_MAXIOV) + 139;
  _SC_IPV6 = _SC_LEVEL1_ICACHE_SIZE + 50;
  _SC_RAW_SOCKETS = (_SC_LEVEL1_ICACHE_SIZE + 50) + 1;
  _SC_V7_ILP32_OFF32 = (_SC_LEVEL1_ICACHE_SIZE + 50) + 2;
  _SC_V7_ILP32_OFFBIG = (_SC_LEVEL1_ICACHE_SIZE + 50) + 3;
  _SC_V7_LP64_OFF64 = (_SC_LEVEL1_ICACHE_SIZE + 50) + 4;
  _SC_V7_LPBIG_OFFBIG = (_SC_LEVEL1_ICACHE_SIZE + 50) + 5;
  _SC_SS_REPL_MAX = (_SC_LEVEL1_ICACHE_SIZE + 50) + 6;
  _SC_TRACE_EVENT_NAME_MAX = (_SC_LEVEL1_ICACHE_SIZE + 50) + 7;
  _SC_TRACE_NAME_MAX = (_SC_LEVEL1_ICACHE_SIZE + 50) + 8;
  _SC_TRACE_SYS_MAX = (_SC_LEVEL1_ICACHE_SIZE + 50) + 9;
  _SC_TRACE_USER_EVENT_MAX = (_SC_LEVEL1_ICACHE_SIZE + 50) + 10;
  _SC_XOPEN_STREAMS = (_SC_LEVEL1_ICACHE_SIZE + 50) + 11;
  _SC_THREAD_ROBUST_PRIO_INHERIT = (_SC_LEVEL1_ICACHE_SIZE + 50) + 12;
  _SC_THREAD_ROBUST_PRIO_PROTECT = (_SC_LEVEL1_ICACHE_SIZE + 50) + 13;
  _SC_MINSIGSTKSZ = (_SC_LEVEL1_ICACHE_SIZE + 50) + 14;
  _SC_SIGSTKSZ = (_SC_LEVEL1_ICACHE_SIZE + 50) + 15;

  { Values for the NAME argument to `confstr'.   }
  { The default search path.   }
const
  _CS_PATH = 0;
  _CS_V6_WIDTH_RESTRICTED_ENVS = 1;
  _CS_GNU_LIBC_VERSION = 2;
  _CS_GNU_LIBPTHREAD_VERSION = 3;
  _CS_V5_WIDTH_RESTRICTED_ENVS = 4;
  _CS_V7_WIDTH_RESTRICTED_ENVS = 5;
  _CS_LFS_CFLAGS = 1000;
  _CS_LFS_LDFLAGS = 1001;
  _CS_LFS_LIBS = 1002;
  _CS_LFS_LINTFLAGS = 1003;
  _CS_LFS64_CFLAGS = 1004;
  _CS_LFS64_LDFLAGS = 1005;
  _CS_LFS64_LIBS = 1006;
  _CS_LFS64_LINTFLAGS = 1007;
  _CS_XBS5_ILP32_OFF32_CFLAGS = 1100;
  _CS_XBS5_ILP32_OFF32_LDFLAGS = 1101;
  _CS_XBS5_ILP32_OFF32_LIBS = 1102;
  _CS_XBS5_ILP32_OFF32_LINTFLAGS = 1103;
  _CS_XBS5_ILP32_OFFBIG_CFLAGS = 1104;
  _CS_XBS5_ILP32_OFFBIG_LDFLAGS = 1105;
  _CS_XBS5_ILP32_OFFBIG_LIBS = 1106;
  _CS_XBS5_ILP32_OFFBIG_LINTFLAGS = 1107;
  _CS_XBS5_LP64_OFF64_CFLAGS = 1108;
  _CS_XBS5_LP64_OFF64_LDFLAGS = 1109;
  _CS_XBS5_LP64_OFF64_LIBS = 1110;
  _CS_XBS5_LP64_OFF64_LINTFLAGS = 1111;
  _CS_XBS5_LPBIG_OFFBIG_CFLAGS = 1112;
  _CS_XBS5_LPBIG_OFFBIG_LDFLAGS = 1113;
  _CS_XBS5_LPBIG_OFFBIG_LIBS = 1114;
  _CS_XBS5_LPBIG_OFFBIG_LINTFLAGS = 1115;
  _CS_POSIX_V6_ILP32_OFF32_CFLAGS = 1116;
  _CS_POSIX_V6_ILP32_OFF32_LDFLAGS = 1117;
  _CS_POSIX_V6_ILP32_OFF32_LIBS = 1118;
  _CS_POSIX_V6_ILP32_OFF32_LINTFLAGS = 1119;
  _CS_POSIX_V6_ILP32_OFFBIG_CFLAGS = 1120;
  _CS_POSIX_V6_ILP32_OFFBIG_LDFLAGS = 1121;
  _CS_POSIX_V6_ILP32_OFFBIG_LIBS = 1122;
  _CS_POSIX_V6_ILP32_OFFBIG_LINTFLAGS = 1123;
  _CS_POSIX_V6_LP64_OFF64_CFLAGS = 1124;
  _CS_POSIX_V6_LP64_OFF64_LDFLAGS = 1125;
  _CS_POSIX_V6_LP64_OFF64_LIBS = 1126;
  _CS_POSIX_V6_LP64_OFF64_LINTFLAGS = 1127;
  _CS_POSIX_V6_LPBIG_OFFBIG_CFLAGS = 1128;
  _CS_POSIX_V6_LPBIG_OFFBIG_LDFLAGS = 1129;
  _CS_POSIX_V6_LPBIG_OFFBIG_LIBS = 1130;
  _CS_POSIX_V6_LPBIG_OFFBIG_LINTFLAGS = 1131;
  _CS_POSIX_V7_ILP32_OFF32_CFLAGS = 1132;
  _CS_POSIX_V7_ILP32_OFF32_LDFLAGS = 1133;
  _CS_POSIX_V7_ILP32_OFF32_LIBS = 1134;
  _CS_POSIX_V7_ILP32_OFF32_LINTFLAGS = 1135;
  _CS_POSIX_V7_ILP32_OFFBIG_CFLAGS = 1136;
  _CS_POSIX_V7_ILP32_OFFBIG_LDFLAGS = 1137;
  _CS_POSIX_V7_ILP32_OFFBIG_LIBS = 1138;
  _CS_POSIX_V7_ILP32_OFFBIG_LINTFLAGS = 1139;
  _CS_POSIX_V7_LP64_OFF64_CFLAGS = 1140;
  _CS_POSIX_V7_LP64_OFF64_LDFLAGS = 1141;
  _CS_POSIX_V7_LP64_OFF64_LIBS = 1142;
  _CS_POSIX_V7_LP64_OFF64_LINTFLAGS = 1143;
  _CS_POSIX_V7_LPBIG_OFFBIG_CFLAGS = 1144;
  _CS_POSIX_V7_LPBIG_OFFBIG_LDFLAGS = 1145;
  _CS_POSIX_V7_LPBIG_OFFBIG_LIBS = 1146;
  _CS_POSIX_V7_LPBIG_OFFBIG_LINTFLAGS = 1147;
  _CS_V6_ENV = 1148;
  _CS_V7_ENV = 1149;


implementation


end.
